// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euaprfhipvmjbsezpnof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1YXByZmhpcHZtamJzZXpwbm9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjQ2NDUsImV4cCI6MjA1ODk0MDY0NX0.0DZRrF9NSmEZA1DQ0ZzssUSLo6frB_tb5JTc6FavGeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);